from . import sucursales_cajas_branch
from . import sucursales_cajas_account
from . import sucursales_cajas_cashbox_line
from . import sucursales_cajas_cashbox
from . import sucursales_cajas_balance
from . import sucursales_cajas_session
from . import sucursales_cajas_operation
from . import res_partner_inherit
from . import chequera_wallet_inherit
from . import res_partner_wallet_inherit